# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180418_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='event_cost',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
            preserve_default=False,
        ),
    ]
