# Generated by Django 2.0.7 on 2018-07-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20180419_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='billed',
            field=models.BooleanField(default=False),
        ),
    ]
