# Generated by Django 2.0.7 on 2018-07-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_billed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='billed',
            field=models.BooleanField(default=False),
        ),
    ]
