# Generated by Django 2.0.7 on 2018-08-03 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_tournament_billed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='billed',
        ),
    ]
