# Generated by Django 2.0.7 on 2018-08-04 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_tournament_billed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='active',
        ),
    ]
