# Generated by Django 2.0.7 on 2018-08-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_tournament_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='tickets',
            field=models.IntegerField(default=0),
        ),
    ]
