# Generated by Django 2.0.7 on 2018-08-08 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20180808_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
    ]
