# Generated by Django 2.0.7 on 2018-08-08 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_remove_event_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_date',
            new_name='date',
        ),
    ]
