# Generated by Django 2.1.2 on 2018-11-14 20:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 11, 14, 20, 49, 5, 560324), verbose_name='Post date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsitem',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
