# Generated by Django 2.1.2 on 2018-11-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20181114_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='image_position',
            field=models.SmallIntegerField(choices=[(0, 'Top, before tite'), (1, 'Top, after title'), (2, 'Left'), (3, 'Right')], default=0),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='summary',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
