# Generated by Django 2.0.4 on 2018-05-11 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20180424_1452'),
        ('diary', '0002_auto_20180510_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='player_1',
        ),
        migrations.AddField(
            model_name='booking',
            name='player_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_4', to='members.Person'),
        ),
    ]
