# Generated by Django 2.0.4 on 2018-05-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20180511_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
