# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandate_id', models.CharField(max_length=50)),
                ('customer_id', models.CharField(max_length=50)),
                ('event_id', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandates', to='members.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.CharField(max_length=30)),
                ('event_id', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=30)),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='members.Payment')),
            ],
        ),
    ]
