# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0039_auto_20171013_1847'),
        ('cardless', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardless',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Person'),
        ),
    ]
