# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0041_auto_20171022_1903'),
        ('cardless', '0004_auto_20171015_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_event',
            old_name='description',
            new_name='action',
        ),
        migrations.RemoveField(
            model_name='payment_event',
            name='person',
        ),
        migrations.AddField(
            model_name='payment_event',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='members.Payment'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandates', to='members.Person'),
        ),
    ]
