# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardless', '0005_auto_20171022_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_event',
            name='created_at',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
