# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineitem',
            old_name='unit_price',
            new_name='sale_price',
        ),
        migrations.AddField(
            model_name='lineitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
