# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, to='members.ItemType'),
        ),
    ]
