# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_auto_20170219_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='billed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
