# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_subscription_resigned'),
        ('pos', '0003_transaction_billed'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='invoice_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.InvoiceItem'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.Layout'),
        ),
    ]
