# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20171125_2023'),
        ('pos', '0003_item_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billed', models.BooleanField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Person')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='split',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pospayment',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.Transaction'),
        ),
    ]
