# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_auto_20171202_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='complementary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Person'),
        ),
    ]
