# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_subscription_resigned'),
        ('pos', '0004_auto_20170329_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layout',
            name='invoice_item',
        ),
        migrations.AddField(
            model_name='layout',
            name='invoice_itemtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.ItemType'),
        ),
    ]
