# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_auto_20171209_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
