# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_posadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='back_colour',
            field=models.CharField(default='#008800', max_length=7),
        ),
        migrations.AddField(
            model_name='item',
            name='fore_colour',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
