# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_auto_20180327_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('fore_colour', models.CharField(default='#ffffff', max_length=7)),
                ('back_colour', models.CharField(default='#008800', max_length=7)),
                ('outline_colour', models.CharField(default='#0000', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='colour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.Colour'),
        ),
    ]
