# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_auto_20180328_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colour',
            name='outline_colour',
        ),
        migrations.RemoveField(
            model_name='item',
            name='back_colour',
        ),
        migrations.RemoveField(
            model_name='item',
            name='fore_colour',
        ),
    ]
