# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-30 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20180327_2358'),
        ('pos', '0010_auto_20180328_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='item_type',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='members.ItemType'),
        ),
        migrations.AlterField(
            model_name='item',
            name='colour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.Colour'),
        ),
    ]
