# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-02 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_auto_20180330_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='terminal',
            field=models.IntegerField(default=1),
        ),
    ]
