# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_auto_20180402_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posadmin',
            name='default_layout',
        ),
        migrations.DeleteModel(
            name='PosAdmin',
        ),
    ]
