# Generated by Django 2.0.4 on 2018-04-24 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_auto_20180411_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.Item'),
        ),
    ]
