# Generated by Django 2.0.6 on 2018-06-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_auto_20180424_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='sub_title',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layout',
            name='title',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
