# Generated by Django 2.0.6 on 2018-06-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0019_auto_20180630_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='layout',
            name='sub_title',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
