# Generated by Django 2.0.6 on 2018-06-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_auto_20180630_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='line_2',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='layout',
            name='line_3',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
