# Generated by Django 2.0.6 on 2018-06-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0021_auto_20180630_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosPing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal', models.SmallIntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
