# Generated by Django 2.0.6 on 2018-07-02 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20180623_0806'),
        ('pos', '0022_posping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=75)),
                ('junior', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('billed', models.BooleanField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Person')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Visitor')),
            ],
        ),
        migrations.AddField(
            model_name='layout',
            name='button_text',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
