# Generated by Django 2.0.6 on 2018-07-08 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0024_visitorfee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitorFee',
        ),
    ]
