# Generated by Django 2.0.6 on 2018-07-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0025_delete_visitorfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorbook',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=6, max_digits=5),
            preserve_default=False,
        ),
    ]
