# Generated by Django 2.0.6 on 2018-07-17 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0026_visitorbook_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=80)),
                ('bar_system', models.BooleanField(default=False)),
                ('main_system', models.BooleanField(default=True)),
                ('index', models.SmallIntegerField()),
                ('layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.Layout')),
            ],
        ),
    ]
