# Generated by Django 2.0.6 on 2018-07-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0028_posapp_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='posapp',
            name='view_name',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
