# Generated by Django 2.0.6 on 2018-07-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0032_auto_20180725_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layout',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='layout',
            name='line_2',
        ),
        migrations.RemoveField(
            model_name='layout',
            name='line_3',
        ),
        migrations.RemoveField(
            model_name='layout',
            name='sub_title',
        ),
    ]
