# Generated by Django 2.0.7 on 2018-08-15 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20180808_1655'),
        ('pos', '0033_auto_20180725_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='posapp',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
