# Generated by Django 2.0.7 on 2018-09-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0034_posapp_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='creation_date',
            field=models.DateTimeField(),
        ),
    ]
