# Generated by Django 2.0.7 on 2018-09-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0035_auto_20180919_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('apps', models.ManyToManyField(to='pos.PosApp')),
            ],
        ),
    ]
