# Generated by Django 2.0.7 on 2018-09-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0036_ticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='apps',
        ),
        migrations.AddField(
            model_name='ticker',
            name='bar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticker',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
