# Generated by Django 2.1.2 on 2018-11-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0037_auto_20180922_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='billed',
        ),

        migrations.AddField(
            model_name='transaction',
            name='billed',
            field=models.SmallIntegerField(choices=[(0, 'Unbilled'), (1, 'Part billed'), (2, 'Billed')], default=0),
        ),
    ]
