# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_itemtype_pos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='hex_key',
            new_name='pin',
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.ItemType'),
        ),
    ]
