# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_person_pays_family_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='gocardless_action',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
