# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20171125_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='allow_marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='consent_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='allow_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='allow_phone',
            field=models.BooleanField(default=False),
        ),
    ]
