# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_invoice_gocardless_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='gocardless_bill_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='gocardless_action',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
