# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20180221_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuniorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('has_needs', models.BooleanField(default=False, verbose_name='Special needs')),
                ('needs', models.TextField(blank=True)),
                ('relationship0', models.CharField(blank=True, max_length=50, verbose_name='Relationship to child')),
                ('contact1', models.CharField(blank=True, max_length=50, verbose_name='Additional contact 1')),
                ('phone1', models.CharField(blank=True, max_length=20, verbose_name='Phone number')),
                ('relationship1', models.CharField(blank=True, max_length=50, verbose_name='Relationship to child')),
                ('contact2', models.CharField(blank=True, max_length=50, verbose_name='Additional contact 2')),
                ('phone2', models.CharField(blank=True, max_length=20, verbose_name='Phone number')),
                ('relationship2', models.CharField(blank=True, max_length=50, verbose_name='Relationship to child')),
                ('photo_consent', models.BooleanField(default=False)),
                ('coaching1', models.BooleanField(default=False, verbose_name='Individual coaching')),
                ('coaching2', models.BooleanField(default=False, verbose_name='Group coaching')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Person')),
            ],
        ),
        migrations.AlterField(
            model_name='adultapplication',
            name='ability',
            field=models.SmallIntegerField(choices=[(0, 'Beginner'), (1, 'Improver'), (2, 'Rusty - Returning to tennis'), (3, 'Intermediate - average club player'), (4, 'Advanced  - club team player')], default=0, verbose_name='Judge your tennis ability'),
        ),
    ]
