# Generated by Django 2.0.4 on 2018-04-24 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20180411_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.ItemType'),
        ),
    ]
