# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_payment_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=20)),
                ('description', models.CharField(max_length=80)),
                ('generated', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='groups',
            field=models.ManyToManyField(to='members.Group'),
        ),
    ]
