# Generated by Django 2.0.4 on 2018-06-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20180424_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='reference',
            new_name='note',
        ),
        migrations.AddField(
            model_name='invoice',
            name='special_case',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cardless_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
