# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20160412_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='generated',
        ),
    ]
