# Generated by Django 2.0.7 on 2018-09-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_visitorfees'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_tennis',
            field=models.BooleanField(default=True),
        ),
    ]
