# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20160831_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailtype',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='unsubscribed',
            field=models.ManyToManyField(to='members.MailType'),
        ),
    ]
