# Generated by Django 2.1.2 on 2018-11-11 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_membership_is_tennis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='cardless_id',
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='Group', max_length=40),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='item_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='item_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.ItemType'),
        ),
    ]
