# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_auto_20160831_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', markdownx.models.MarkdownxField()),
            ],
        ),
    ]
