# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtype',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mailtype',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
