# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-25 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_auto_20160911_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='textblock',
            name='type',
            field=models.SmallIntegerField(choices=[(0, b'Text block'), (1, b'HTML document'), (2, b'Bee editor template')], default=0),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='text',
            field=models.TextField(),
        ),
    ]
