# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_auto_20160925_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('sent_date', models.DateTimeField()),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.TextBlock')),
            ],
        ),
        migrations.AddField(
            model_name='mailtype',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.MailCampaign'),
        ),
    ]
