# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_auto_20161002_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('json', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='mailtype',
            old_name='campaign',
            new_name='mail_campaign',
        ),
        migrations.RemoveField(
            model_name='mailcampaign',
            name='template',
        ),
        migrations.AddField(
            model_name='mailcampaign',
            name='mail_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.MailTemplate'),
        ),
    ]
