# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-03 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_auto_20161002_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailcampaign',
            name='json',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mailcampaign',
            name='sent_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mailcampaign',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
