# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-03 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_auto_20161003_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailcampaign',
            name='json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
