# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_auto_20161003_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailcampaign',
            options={'ordering': ['-update_date']},
        ),
        migrations.AddField(
            model_name='person',
            name='sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Subscription'),
        ),
    ]
