# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_auto_20170107_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_adult',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='is_playing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='description',
            field=models.CharField(max_length=20, verbose_name=b'Membership'),
        ),
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name=b'Date of birth'),
        ),
    ]
