# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_auto_20170120_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='cutoff_age',
            field=models.IntegerField(default=0),
        ),
    ]
