# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-23 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_subscription_resigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='state',
            field=models.SmallIntegerField(choices=[(0, b'Unpaid'), (1, b'Part paid'), (2, b'Paid'), (3, b'Cancelled'), (4, b'Part paid & credit note'), (5, b'Error - overpaid'), (6, b'Pending GoCardless')], default=0),
        ),
    ]
