# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-12 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_auto_20170423_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdultApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.SmallIntegerField(choices=[(0, b'Beginner'), (1, b'Improver'), (2, b'Rusty - Returning to tennis'), (3, b'Intermediate - average club player'), (4, b'Advanced  - club team player')], default=0)),
                ('singles', models.BooleanField(default=False, verbose_name=b'Singles')),
                ('doubles', models.BooleanField(default=False, verbose_name=b'Doubles')),
                ('coaching1', models.BooleanField(default=False, verbose_name=b'Individual coaching')),
                ('coaching2', models.BooleanField(default=False, verbose_name=b'Group coaching')),
                ('daytime', models.BooleanField(default=False, verbose_name=b'Daytime tennis')),
                ('family', models.BooleanField(default=False, verbose_name=b'Family tennis')),
                ('social', models.BooleanField(default=False, verbose_name=b'Social tennis')),
                ('competitions', models.BooleanField(default=False, verbose_name=b'Club competitions')),
                ('teams', models.BooleanField(default=False, verbose_name=b'Team tennis')),
                ('club', models.CharField(max_length=30, verbose_name=b'Club name')),
                ('source', models.SmallIntegerField(choices=[(0, b'Friend, relative or member'), (1, b'School'), (2, b'Web search'), (3, b'LTA search or promotion'), (4, b'Leaflet'), (5, b'Advertisement'), (6, b'Other')], default=2)),
                ('membership', models.SmallIntegerField(choices=[(1, b'Full'), (15, b'Off peak'), (14, b'Parent'), (4, b'Under 26')], default=1)),
                ('rules', models.BooleanField(default=False, verbose_name=b'I agree')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Person')),
            ],
        ),
    ]
