# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 20:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0027_adultapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='auth',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='hex_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultapplication',
            name='ability',
            field=models.SmallIntegerField(choices=[(0, b'Beginner'), (1, b'Improver'), (2, b'Rusty - Returning to tennis'), (3, b'Intermediate - average club player'), (4, b'Advanced  - club team player')], default=0, verbose_name=b'Judge your tennnis ability'),
        ),
        migrations.AlterField(
            model_name='adultapplication',
            name='club',
            field=models.CharField(max_length=30, verbose_name=b'Name of previous tennis club (if any)'),
        ),
        migrations.AlterField(
            model_name='adultapplication',
            name='membership',
            field=models.SmallIntegerField(choices=[(13, b'No membership (parent)'), (1, b'Full membership'), (15, b'Off peak (Mon - Fri to 6pm)'), (14, b'Parent - to play with children'), (4, b'Under 26')], default=1, verbose_name=b'Membership category'),
        ),
        migrations.AlterField(
            model_name='adultapplication',
            name='rules',
            field=models.BooleanField(default=False, verbose_name=b'I agree to abide by the club rules'),
        ),
        migrations.AlterField(
            model_name='adultapplication',
            name='source',
            field=models.SmallIntegerField(choices=[(0, b'Friend, relative or member'), (1, b'School'), (2, b'Web search'), (3, b'LTA search or promotion'), (4, b'Leaflet'), (5, b'Advertisement'), (6, b'Other')], default=2, verbose_name=b'How did you hear about us?'),
        ),
    ]
