# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_auto_20170524_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='allow_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='allow_phone',
            field=models.BooleanField(default=True),
        ),
    ]
