# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 06:49
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0030_auto_20170625_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='text',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
