# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0032_adultapplication_membership_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adultapplication',
            name='membership_type',
        ),
        migrations.RemoveField(
            model_name='adultapplication',
            name='rules',
        ),
        migrations.AlterField(
            model_name='adultapplication',
            name='membership',
            field=models.SmallIntegerField(choices=[(1, b'Full'), (15, b'Off peak'), (14, b'Parent'), (6, b'Country'), (5, b'Bridge'), (11, b'Non playing'), (7, b'Coach'), (4, b'Under 26'), (8, b'Honorary life'), (7, b'Coach')], default=1, verbose_name=b'Membership type'),
        ),
    ]
