# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0035_auto_20170719_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='apply_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='long_description',
            field=models.CharField(blank=True, max_length=300, verbose_name=b'Description'),
        ),
    ]
