# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0036_auto_20170727_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='apply_online',
            field=models.BooleanField(default=True),
        ),
    ]
