# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0037_auto_20170729_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adultapplication',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Person'),
        ),
    ]
