# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0039_auto_20170919_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cardless_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
