# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0040_auto_20171015_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cardless_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='pending',
        ),
        migrations.AddField(
            model_name='payment',
            name='pay_state',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Paid'), (2, 'Failed'), (3, 'Cancelled')], default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'Unpaid'), (1, 'Pending'), (2, 'Paid'), (3, 'Cancelled'), (4, 'Underpaid'), (5, 'Overpaid')], default=0),
        ),
    ]
