# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0041_auto_20171022_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='state',
            new_name='match_state',
        ),
    ]
