# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0042_auto_20171023_0808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='pay_state',
            new_name='state',
        ),
    ]
