# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0043_auto_20171023_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='cardless_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='members.Invoice'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'Unpaid'), (2, 'Paid'), (3, 'Cancelled'), (4, 'Underpaid'), (5, 'Overpaid')], default=0),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='members.Invoice'),
        ),
    ]
