# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0044_auto_20171024_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Invoice'),
        ),
    ]
