# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0045_auto_20171026_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payments_expected',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_number',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'Unpaid'), (1, 'Part paid'), (2, 'Paid'), (3, 'Cancelled'), (4, 'Overpaid')], default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Confirmed'), (2, 'Failed'), (3, 'Cancelled')], default=0),
        ),
    ]
