# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0046_auto_20171029_1912'),
        ('members', '0039_auto_20170919_0721'),
    ]

    operations = [
    ]
