# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0039_auto_20171013_1847'),
        ('members', '0039_auto_20170917_1853'),
        ('members', '0047_merge_20171031_1659'),
    ]

    operations = [
    ]
